const fs = require('fs');
const file = 'src/app/components/pages/ReviewPage.tsx';
let code = fs.readFileSync(file, 'utf8');

const startMarker = '  // --- Overlay Component for Question Review ---';
const startIndex = code.indexOf(startMarker);
const endMarker = '  // Process data for the new sections';
const endIndex = code.indexOf(endMarker);

let overlayCode = code.substring(startIndex, endIndex).trim();

overlayCode = overlayCode.replace(
    '{ responses, currentIndex, onClose, onPrev, onNext, showAnswer, setShowAnswer }: any',
    '{ responses, currentIndex, onClose, onPrev, onNext, showAnswer, setShowAnswer, latestResult, apiBase }: any'
);

code = code.substring(0, startIndex) + code.substring(endIndex);

const exportIdx = code.indexOf('export function ReviewPage');
code = code.substring(0, exportIdx) + overlayCode + '\n\n' + code.substring(exportIdx);

// Add missing props
code = code.replace(
    'setShowAnswer={setShowAnswer}',
    'setShowAnswer={setShowAnswer}\n            latestResult={latestResult}\n            apiBase={apiBase}'
);

const aiOld = `        {/* Analysis Section */}
        {latestResult.ai_suggestions && (
          <section className="space-y-8 pt-12 border-t border-white/10">`;

const aiNew = `        {/* Analysis Section */}
        {latestResult.ai_suggestions ? (
          <section className="space-y-8 pt-12 border-t border-white/10">`;
code = code.replace(aiOld, aiNew);

const aiEndOld = `            </div>
          </section>
        )}
      </div>
    </div>
  );
}`;

const aiEndNew = `            </div>
          </section>
        ) : (
          <section className="space-y-8 pt-12 border-t border-white/10 flex flex-col items-center justify-center py-12">
            <Brain className="w-16 h-16 text-indigo-500/50 mb-4" />
            <h2 className="text-2xl font-black text-white tracking-tight mb-2">AI Performance Analysis</h2>
            <p className="text-slate-400 mb-8 text-center max-w-md">Get personalized insights and a study roadmap generated by our advanced AI model based on your test performance.</p>
            <button
               onClick={handleAnalyzePerformance}
               disabled={isAnalyzing}
               className="px-8 py-4 bg-indigo-600 hover:bg-indigo-500 transition-colors text-white font-bold rounded-2xl flex items-center gap-3 disabled:opacity-50"
            >
               {isAnalyzing ? (
                 <>
                   <Loader2 className="w-5 h-5 animate-spin" />
                   Analyzing...
                 </>
               ) : (
                 <>
                   <Sparkles className="w-5 h-5" />
                   Generate AI Review
                 </>
               )}
            </button>
          </section>
        )}
      </div>
    </div>
  );
}`;
code = code.replace(aiEndOld, aiEndNew);

fs.writeFileSync(file, code);
console.log('Fix applied successfully.');
